config/routes.rb
Rails.application.routes.draw do

  resources :wikis

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges,  only: [:new, :create, :destroy]

  get '/charges', to: 'charges#destroy', as: :downgrade

  devise_for :users

  get 'about' => 'welcome#about'
  root 'welcome#index' do
    resources :wikis, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
	belongs_to :user
	belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  has_many :collaborators
  has_many :wikis, through: :collaborators

  after_initialize { self.role ||= :standard }

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators

  after_initialize { self.private ||= false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  @user = User.friendly.find(params[:id])
  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    # Amount in cents
    @amount = 1500

    # Creates a Stripe Customer object, for associating with the charge.
    @customer = Stripe::Customer.create(
      :email =>  params[:stripeEmail],
      :card  =>  params[:stripeToken]
    )

    # Where the real magic happens
    @stripe_charge = Stripe::Charge.create(
      :customer    =>    @customer.id, # Note -- thise is NOT the user_id in this app.
      :amount      =>    @amount,
      :description =>    "Stripe customer",
      :currency    =>    "usd"
    )

    current_user.premium!
    flash[:notice] = "Thanks for upgrading to a premium account, #{current_user.email}!"
    redirect_to edit_user_registration_path


    @plan = Stripe::Plan.retrieve("premium")
    unless @plan
      plan = Stripe::Plan.create(
        :name => "Premium",
        :id => "premium",
        :interval => "month",
        :currency => "usd",
        :amount => 1500
      )

      @subscription = Stripe::Subcription.create(
        :customer => customer.id,
        :plan => "premium",
      )

      #redirect_to root_path
    end

    # Stripe will send back CardErrors, with friendly messages.
    # when something goes wrong.
    # This 'rescue block' catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key:         "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Omniwiki Membership - #{current_user.email}",
      amount:      @amount
    }
  end

  def destroy
    current_user.standard!

    flash[:notice] = "Your account has been downgraded to a standard account. Your private wikis are now public. You will recieve a $15.00 refund."
    redirect_to root_path
  end
end

app/controllers/collaborator_controller.rb
class CollaboratorController < ApplicationController
  before_action :get_current_wiki

  def index
    @user = User.all
  end

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki_id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator add."
    else
      flash[:alert] = "Error occured. Please try again."
    end

    redirect_back fallback_location: root_path
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed"
    else
      flash[:alert] = "Error occured. Please try again."
    end

    redirect_back fallback_location: root_path
  end

  private

  def get_current_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :get_current_wiki

  def index
    @user = User.all
  end

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator added."
    else
      flash[:alert] = "Error occured. Please try again."
    end

    redirect_back fallback_location: root_path
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed"
    else
      flash[:alert] = "Error occured. Please try again."
    end

    redirect_back fallback_location: root_path
  end

  private

  def get_current_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show
  def show
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Your entry was saved."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was a problem saving your entry. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    @get_wikis = Collaborator.where(wiki_id: @wiki.id)
    @collaborators = User.where(id: @get_wikis.pluck(:user_id))
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Your entry was updated."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving your entry. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error deleting your entry."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :quote, :body, :sources, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def form_group_tag(errors, &block)
		css_class = 'form-group'
		css_class << 'has-error' if errors.any?
		content_tag :div, capture(&block), class: css_class
	end

	def markdown(text)
		require 'redcarpet'
		options = {
						:fenced_code_blocks => 	 true,
						:filter_html => 			 	 true,
						:hard_wrap => 				 	 true,
						:link_attributes => 	 	 { rel: 'nofollow', target: "_blank" },
						:space_after_headers =>  true
		}

		extensions = {
							 :autolink => 	 true,
							 :superscript => true,
							 :quote => 			 true,
		}

		renderer = Redcarpet::Render::HTML.new(options)
		markdown = Redcarpet::Markdown.new(renderer, extensions)
		markdown.render(text).html_safe
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
	def is_user_collaborator?(id, collaborators)
		collaborators.find { |user| user[:id] == id }
	end
end

app/views/charges/_downgrade.html.erb
<%= link_to "Downgrade Account", downgrade_path, :class => 'btn btn-danger', data: { confirm: 'Are you sure you want to go back to a standard account? Your private wikis will be made public and you will have to pay again to upgrade your account to premium later.' } %>

app/views/charges/create.html.erb
<!--<h2>Thanks, you paid <strong>$15.00></strong></h2>-->

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
	<% if current_user.role == 'standard' %>
		<h4>Upgrade your account!</h4>
		<hr>
		<p>Your current membership level is : <strong><%= current_user.role %></strong></p>
		<article>
			<% if flash[:error].present? %>
				<div id="error_explanation">
					<p><%= flash[:error] %></p>
				</div>
			<% end %>
			<label class="amount">
				<span>Amount: <strong>$15.00</strong></span>
			</label>
		</article>
		<script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
						data-key="<%= @stripe_btn_data[:key] %>"
						data-amount="<%= @stripe_btn_data[:amount] %>"
						data-description="<%= @stripe_btn_data[:description] %>" >
		</script>
	<% elsif current_user.role == 'premium' %>
		<h4>Downgrade your account</h4>
		<hr>
		<p>Your current membership level is : <strong><%= current_user.role %></strong></p>
  	<%= render partial: 'downgrade' %>
	<% end %>
<% end %>

app/views/collaborator/_form.html.erb
<div class="modal fade collaborator-modal-lg" id="collaboratorModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Manage Collaborators</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<table class="table">
						<tr>
							<th>User Email</th>
							<th>Collaborator</th>
						</tr>
						<% @users.each do |user| %>
							<% if user.id != @wiki.user_id %>
								<tr>
									<td><%= user.email %></td>
									<td>
										<% if is_user_collaborator?(user.id, @collaborators) %>
											<%= link_to "Remove", wiki_collaborator_path(@wiki.id, @wiki.collaborator.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
										<% else %>
											<%= link_to "Add", wiki_collaborator_index_path(@wiki.id, user_id: user.id), method: :post, class: 'btn btn-success' %>
										<% end %>
									</td>
								</tr>
							<% end %>
						<% end %>
					</table>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Save Changes</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/collaborators/_form.html.erb
<div class="modal fade collaborator-modal-lg" id="collaboratorsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Manage Collaborators</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<table class="table">
						<tr>
							<th>User Email</th>
							<th>Collaborator</th>
						</tr>
						<% @users.each do |user| %>
							<% if user.id != @wiki.user_id %>
								<tr>
									<td><%= user.email %></td>
									<td>
										<% if is_user_collaborator?(user.id, @collaborators) %>
											<%= link_to "Remove", wiki_collaborator_path(@wiki.id, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
										<% else %>
											<%= link_to "Add", wiki_collaborators_path(@wiki.id, user_id: user.id), method: :post, class: 'btn btn-success' %>
										<% end %>
									</td>
								</tr>
							<% end %>
						<% end %>
					</table>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Save Changes</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/collaborators/create.html.erb
<h1>Collaborator#create</h1>
<p>Find me in app/views/collaborator/create.html.erb</p>

app/views/collaborators/index.html.erb
<h1>Collaborator#index</h1>
<p>Find me in app/views/collaborator/index.html.erb</p>

app/views/collaborators/new.html.erb
<h1>Collaborator#new</h1>
<p>Find me in app/views/collaborator/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omniwiki</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="pull-right login">
        <% if user_signed_in? %>
         <strong><%= current_user.email %> - <%= current_user.role %></strong> | <%= link_to 'Edit account', edit_user_registration_path, :class => 'nav-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        <% else %>
         <%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link'  %>
        <% end %>
      </div>
      <ul class="nav nav-tabs">
        <li><%= link_to "Omniwiki", root_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Membership", new_charge_path %></li>
      </ul>

      <% if flash[:success] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<center><h1>About</h1></center>
<hr>
<br>
<p>Omniwiki is a wiki encyclopedia app made using Ruby on Rails that allows users to create public and private Markdown-based wikis.</p>

app/views/welcome/index.html.erb
<% if notice %>
	<div class="alert alert-warning" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p><%= flash[:notice] %></p>
	</div>
<% end %>
<div class="jumbotron">
	<h1>Omniwiki</h1>
	<h3>We have all the wikis!</h3>
</div>
<div class="container">
	<div class="media-heading">
		<h4><strong>A Random Wiki</strong></h4>
	</div>
	<hr>
	<div class="wiki-title">
		<h3><%= Faker::Hobbit.location %></h3>
	</div>
	<div class="panel panel-default">
		<div class="panel-body">
			<blockquote class="blockquote mb-0">
				<p><%= Faker::BackToTheFuture.quote %></p>
				<footer class="blockquote-footer text-dark">Someone famous</footer>
    	</blockquote>
		</div>
	</div>
	<div class="row">
	<div class="col-md-8">
		<p><%= Faker::Lorem.paragraph([rand(50), rand(100)], false) %></p>
	</div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
	<% if wiki.errors.any? %>
		<div class="alert alert-danger">
			<h4><%=pluralize(wiki.errors.count, "error") %>.</h4>
			<ul>
				<% wiki.errors.full_messages.each do |msg| %>
					<li><%= msg %>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div "form-group">
		<%= form_group_tag(wiki.errors[:title]) do %>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control', placeholder: 'Enter Wiki Title' %>
		<% end %>
		<%= form_group_tag(wiki.errors[:quote]) do %>
			<%= f.label :quote %>
			<%= f.text_field :quote, class: 'form-control', placeholder: 'Enter Quote' %>
		<% end %>
		<%= form_group_tag(wiki.errors[:body]) do %>
			<%= f.label :body %>
			<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter Your Wiki Entry Here' %>
		<% end %>
		<%= form_group_tag(wiki.errors[:sources]) do %>
			<%= f.label :sources %>
			<%= f.text_area :sources, rows: 5, class: 'form-control', placeholder: 'List Your Sources Here' %>
		<% end %>
		<% if current_user.admin? || current_user.premium? %>
			<%= f.label :private do %>
				<%= f.check_box :private, checked: @wiki.private %> Private wiki
			<% end %>
		<% end %>
	</div>
	<% if @wiki.private? && current_user.admin? || current_user.id == @wiki.user_id %>
		<div class="form-group">
			<%= render partial: 'collaborators/form', locals: { wiki: @wiki } %>
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".collaborator-modal-lg">
				Manage Collaborators
			</button>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.submit "Save", class: 'btn btn-success' %>
	</div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Your Wiki</h1>
<div class="row">
	<div class="col-md-4">
		<p>Bacon ipsum dolor amet esse commodo jerky excepteur adipisicing ad. Est pork swine strip steak.<p>
		<ul>
			<li>Jowl non fatback leberkas nostrud.</li>
			<li>Flank shankle spare ribs in in nisi.</li>
			</li>Tenderloin in dolore consectetur id t-bone ullamco veniam.</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { wiki: @wiki } %>
	</div>
</div>

app/views/wikis/index.html.haml
%h1
	All The Wikis
%hr
.div.class-row
	.class-col-md-8">
		- @wikis.each do |wiki|
			.class-media
				.class-media-body
					%h4.class-media-heading
						%p
							= link_to markdown(wiki.title), wiki_path(wiki.id)
	.div.class-col-md-4
		= link_to "New Wiki", new_wiki_path, class: 'btn btn-success'

app/views/wikis/new.html.erb
<h1>New Wiki Entry</h1>
<div class="row">
	<div class="col-md-4">
		<p>Bacon ipsum dolor amet doner ground round chuck capicola picanha turducken</p>
		<ul>
			<li>Meatloaf doner flank andouille meatball.</li>
			<li>Porchetta doner ball tip leberkas, beef cupim bresaola turkey shank venison salami fatback alcatra shankle.</li>
			<li>Pastrami capicola rump, andouille strip steak sirloin buffalo burgdoggen ball tip.</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { wiki: @wiki } %>
	</div>
</div>

app/views/wikis/show.html.erb
<div>
	<div class="page-header">
		<h1><%= markdown(@wiki.title) %>
			<small class="text-muted"><%= @wiki.user.email %></small>
		</h1>
	</div>
	<div class="panel panel-default">
		<div class="panel-body">
			<blockquote class="blockquote mb-0">
				<p><%= markdown(@wiki.quote) %></p>
				<footer class="blockquote-footer text-dark">Someone famous</footer>
    	</blockquote>
		</div>
	</div>
	</br>
</div>
<div class="row">
	<div class="col-md-8">
		<p><%= markdown(@wiki.body) %></p>
		<br>
		<div class="panel panel-default">
			<div class="panel-body">
				<p><%= markdown(@wiki.sources) %></p>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
		<%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this Wiki?' } %>
	</div>
	<div class="col-md-8">
		<% if current_user.premium? || current_user.admin? %>
			<h3>Collaborators</h3>
			<% @wiki.collaborators.each do |c| %>
				<% user = User.find(c.user_id) %>
				<%= user.email %>
			<% end %>
		<% end %>
	</div>
</div>